### ISSUE TITLE
Multiple errors after updating kexts (Intel EFI)

### ISSUE THREAD

**Issue by JoseRitoPortugalLaurean** [Hasodikis/Thinkpad-T460-Hackintosh#1]
First I updated the kexts on the EFI using Hackintool, then using OCAuxiliaryTools. The first problem using Hackintool is that after updating VoodooRMI, VoodooPS2Controler and VoodooSMBus the physical click keys are not recognized, then after removing SMBus and PS2Controller and updating the config.plist (because in other EFIs I made mouse and keyboard works fine with only PS2Controller), the mouse and keyboard are no longer functional.

The second one comes when I update all of the outdated kexts using OCAuxiliaryTools (with the OpenCore 0.9.3 database in it). The first thing shown on the program are all of these errors.
![image](https://github.com/Hasodikis/Thinkpad-T460-Hackintosh/assets/126290786/a5103b48-6aad-40ae-8b40-c5fdd7c4b1da)
![image](https://github.com/Hasodikis/Thinkpad-T460-Hackintosh/assets/126290786/44e30352-9fb7-4af2-a665-04c4eb2ffdcc)

The first errors that include "Base" and "BaseSkip" are automatically solved whenever i click on save config, but the other one about PciRoot remains still unless I delete the number 2 at the end of the rule.

Then, i click update and update all of the kexts that appear as outdated, almost all of the actually.
![Captura de pantalla 2023-07-09 a la(s) 14 38 58](https://github.com/Hasodikis/Thinkpad-T460-Hackintosh/assets/126290786/823279cd-e2ab-411a-98af-e27e1c68dc37)
![Captura de pantalla 2023-07-09 a la(s) 14 39 06](https://github.com/Hasodikis/Thinkpad-T460-Hackintosh/assets/126290786/7487731a-4d10-49f1-b577-0c68fdaf429a)
![Captura de pantalla 2023-07-09 a la(s) 14 39 15](https://github.com/Hasodikis/Thinkpad-T460-Hackintosh/assets/126290786/74c4f104-c7ae-4385-bc75-7101a0c6b8f3)

When i save and restart to check if worked. Trackpad don't work and few seconds after logging in, it shows a black screen and reboots. I would like to help with this development because of the kexts, plus adding some more that can and will expand the posibilities of a Hackintosh.

**Comment by JoseRitoPortugalLaurean** [comment]
I know perfectly Voodoo updates breaks the trackpad and keyboard, but the rest of the kexts are messing up my device

**Comment by Hasodikis** [comment]
First of all never update your kexts using hackintool or any other program. Always do it manually.
Secondly if you have a stable system or unless there is some new features or error correction, don’t update your kexts. 
Regarding the pciroot error I will try and reproduce it.
Did you update the efi to open core 0.9.3 before you perform the checks.?

The issue with the voodoo input can be corrected but I don’t have the time to do it now

**Comment by Hasodikis** [comment]
Just delete n 2 at the end of the specific pciroot in device propertiesin config.plist. It is an error on my part

**Comment by JoseRitoPortugalLaurean** [comment]
Thanks Hasodikis
