### ISSUE TITLE
EFI (Intel) Issue

### ISSUE THREAD

**Issue by Gostrdr1337** [Hasodikis/Thinkpad-T460-Hackintosh#2]
When attempting to boot the computer with the installed EFI (Intel), there is an issue where the computer gets stuck at the startup screen and does not proceed further. There are no signs of activity or progress in the system booting process.

Does anyone know what could be causing this?
![IMG_2023-07-10-08-18-28-453](https://github.com/Hasodikis/Thinkpad-T460-Hackintosh/assets/106471686/660fde00-8fd4-420f-9af1-2d53ca2643b1)

**Comment by Hasodikis** [comment]
Is your bios configured correctly?
Is your laptop a t460 and not t460s?
Did you make any changes to the EFI?

**Comment by Gostrdr1337** [comment]
> Is your bios configured correctly? Is your laptop a t460 and not t460s? Did you make any changes to the EFI?

Yes, the BIOS is configured correctly as per the recommended settings. My laptop is a T460, not a T460s. I have made changes to the SMBIOS configuration in the EFI file.

**Comment by Hasodikis** [comment]
Upload the EFI you are using. 
Also tell me your bios Version and what type of ssd you are using

**Comment by Gostrdr1337** [comment]
I'm using yours (intel efi) I didn't change anything except smbios. Here is the information about my BIOS version and the SSD used:

BIOS version: R06ET71W (1.45)
SSD: SAMSUNG MZ7LN256HCHP-000L7 - 256.0 GB

Let me know if you need more details.

**Comment by Hasodikis** [comment]
Try in Misc-> Security->SecureBootModel-> Disabled

**Comment by Gostrdr1337** [comment]
> Try in Misc-> Security->SecureBootModel-> Disabled

Doesn't work

**Comment by Hasodikis** [comment]
try booting with the broadcom efi  but first Misc-> Security->SecureBootModel-> Disabled

**Comment by Gostrdr1337** [comment]
> try booting with the broadcom efi  but first Misc-> Security->SecureBootModel-> Disabled

Doesn't work

**Comment by Hasodikis** [comment]
Upload your efi here so that I can take a look
