### ISSUE TITLE
Can't boot from a flash drive using your EFI (Intel)

### ISSUE THREAD

**Issue by Roma15228** [Hasodikis/Thinkpad-T460-Hackintosh#3]
Throws an error at startup
![IMG20230722105531.jpg](https://github.com/Hasodikis/Thinkpad-T460-Hackintosh/assets/60067543/2c69edff-8e37-4ced-90fb-3954eb8b2177)

**Comment by Roma15228** [comment]
![IMG20230722105531.jpg](https://github.com/Hasodikis/Thinkpad-T460-Hackintosh/assets/60067543/8f9fa3f6-a3f9-412c-8456-b6437cdf5e80)

Here is the error (Sorry if I didn't format it correctly, this is my first time doing this)

**Comment by Roma15228** [comment]
![IMG20230722105531.jpg](https://github.com/Hasodikis/Thinkpad-T460-Hackintosh/assets/60067543/8f9fa3f6-a3f9-412c-8456-b6437cdf5e80)

Here is the error (Sorry if I didn't format it correctly, this is my first time doing this)

**Comment by Hasodikis** [comment]
Did you change the bios settings to the recommended?
If yes and still have the problem change in config.plist securebootmodel to Disabled (capital D)

**Comment by Hasodikis** [comment]
See in https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/opencore-issues.html#oc-failed-to-find-sb-model-disable-halting-on-critical-error

**Comment by Roma15228** [comment]
> Did you change the bios settings to the recommended?
> If yes and still have the problem change in config.plist securebootmodel to Disabled (capital D)

I set the recommended settings. When I get home I will try to correct plist

**Comment by Roma15228** [comment]
> See in https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/opencore-issues.html#oc-failed-to-find-sb-model-disable-halting-on-critical-error

I wanted to clarify, the latest version is suitable for installation monterey?

**Comment by Hasodikis** [comment]
I dont see why it shouldn' t be.

**Comment by Roma15228** [comment]
> I dont see why it shouldn' t be.

Ok, I will try, I will unsubscribe here.

**Comment by Roma15228** [comment]
> I dont see why it shouldn' t be.

Ok, I will try, I will unsubscribe here.

**Comment by Roma15228** [comment]
> I dont see why it shouldn' t be.

Sorry for my stupidity, but I better clarify. 1.Why are there two folders in the archive Efi abd Macosx
2.Do I need to fill in something in the config in addition to what you wrote above

**Comment by Hasodikis** [comment]
You better start reading my friend... 
https://dortania.github.io/OpenCore-Install-Guide/
